sudo: yes

services:
  - docker

language: java

# Travis is configured to run on pushed branches and pull requests so if we don't filter branches it runs twice when
# we push the PR branch in our repo
branches:
  only:
    - master
    #tag xx.yy-zz or xx.yy.zz-anythinglikeexperimental
    - /^\d+\.\d+(\.\d+)?(-\S*)?$/
    #hotfix branches (not being too strict on purpose)
    - /^hf-.*$/

before_install:
  - docker pull feedzai/oracle-jep-miniconda:1.0.1
  - docker run -v $(pwd):/opt/openml -d --name test-container feedzai/oracle-jep-miniconda:1.0.1 top -b

install:
  - docker exec -it test-container bash -v /opt/openml/scripts/maven-with-jep.sh install -f /opt/openml/pom.xml -DskipTests=true -Dmaven.javadoc.skip=true -B -V

script:
  - docker exec -it test-container bash -v /opt/openml/scripts/maven-with-jep.sh -f /opt/openml/pom.xml test

after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
    # enables comments in the branch with the CI results
    webhooks: https://www.travisbuddy.com/

before_deploy:
  # Clean up all target dirs created by mvn inside the container so that the deploy script works (permission errors)
  - docker exec -it test-container bash -v mvn -f /opt/openml/pom.xml clean

deploy:
  provider: script
  script: deploy/deploy.sh
  on:
    tags: true
